version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4040:4040
    volumes:
      - ./frontend:/app

  